stages:
  - build

variables:
  APPLICATION_NAME: face-recognition-fastapi
  CONTAINER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CONTAINER_IMAGE_X86: ${CONTAINER_IMAGE}:x86
  CONTAINER_IMAGE_AARCH64: ${CONTAINER_IMAGE}:aarch64

build-aarch64:
  stage: build
  tags:
    - aarch64
  script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    - docker build -f Dockerfile_aarch64 -t ${CONTAINER_IMAGE_AARCH64} .
    - docker push ${CONTAINER_IMAGE_AARCH64}
    - docker image rm ${CONTAINER_IMAGE_AARCH64} || echo "Image is currently used"

build-x86:
  stage: build
  tags:
    - x86
  script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    - docker build -f Dockerfile_x86 -t ${CONTAINER_IMAGE_X86} .
    - docker push ${CONTAINER_IMAGE_X86}
    - docker image rm ${CONTAINER_IMAGE_X86}
