apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APPLICATION_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
      - name: ${APPLICATION_NAME}
        image: ${CONTAINER_IMAGE_X86}
        ports:
        - containerPort: 80
        env:
        - name: MONGODB_URL
          value: mongodb://192.168.1.2
        - name: AUTHENTICATION_URL
          value: https://api.authentication.maximemoreillon.com/whoami
        volumeMounts:
        - mountPath: /usr/src/app/uploads
          name: ${APPLICATION_NAME}
      volumes:
      - name: ${APPLICATION_NAME}
        persistentVolumeClaim:
          claimName: ${APPLICATION_NAME}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  type: NodePort
  selector:
    app: ${APPLICATION_NAME}
  ports:
  - port: 80
    nodePort: 30021
